### ISSUE TITLE
How to install magnolial

### ISSUE THREAD

**Issue by crakdown-25** [eflynch/magnolial#3]
Hi,

First thank's for his great project. I search alternative to workflowy and this project seems to be perfect.

Can you prerequisite give some details about prerequisite(s) and install process.
I try to put the content of the app dir into my server but it not working.

Thank's a lot

**Comment by eflynch** [comment]
Hi,

I have to be honest, I haven't touched this project in a long time and I'm not sure exactly the state of it. If you want to use, you will likely want to fork it and modify it to fit your need.

As far as installing it, it can work as an Electron app or a standalone web app. The Electron project has evolved a fair bit since I was using it in 2016, so it might take a little digging to get it working with the latest APIs.

The files that actually interact with the Electron framework and file system are src/node-io.js and app/main.js.

Also a word of warning, the keybindings I have by default are pretty idiosyncratic as is the file saving interface...

**Comment by eflynch** [comment]
If you want to take a stab at it, I would look at those files. I think the code quality is pretty decent if I recall. The webpack config and node dependencies no doubt need to be upgraded.

**Comment by eflynch** [comment]
A bit more up-to-date implementation of the core functionality can be found here:
https://github.com/eflynch/evanlyn.ch/blob/master/src/magnolial.js

**Comment by crakdown-25** [comment]
Hi,

Thank's for your reply.
I try to download https://github.com/eflynch/evanlyn.ch project and to copy/adapt src directory into my serveur (I user Yunohost portal to host several app).
Even if I download/copy all library to good path (jquery, bootstrap) the result look likes your website but I don't have the dynamic part ... :(

The problem is maybe I create a index.html file using the "view source of" func of Firefox (because the index.html file is missing in project).

I think I'm not in the good direction...

**Comment by eflynch** [comment]
The version in evanlyn.ch doesn't have any dynamic state as it's a statically hosted website. (It does load from session state, but that is local). The magnolial.js file there is just a more up-to-date version of the main React component that is in the original magnolial project.

If I went back to this project, I would probably try to use https://react-redux.js.org/ to make create a dynamic front-end with a basic CRUD server behind it. You will likely need to do some careful reading of the source and do some real development to make this project suit your needs.

**Comment by eflynch** [comment]
I might take this project on at some point, probably not immediately. If you give it a go, let me know.

**Comment by crakdown-25** [comment]
Ok, I understand better why it's not working how I expected.
Thank's for your advice but unfortunatly I not a power front-end developer, I don't think I try to pip your project :/

Best regards

**Comment by eflynch** [comment]
Just an update here. I actually went ahead and rewrote a lot of this project. The new version is on the branch "next." I'll probably merge it to the main at some point. It might be a bit closer to what you want.

There is a web client which is basically fully functional on it it's own, but then there is a Flask server which can serve it and back it with a psql database. The client will try to keep it synced up as you make changes.

**Comment by eflynch** [comment]
It's now merged to master

**Comment by crakdown-25** [comment]
Hello,

Thank's for this update :)

**Comment by eflynch** [comment]
Another update... I'm going to try to integrate this project with sandstorm.io soon
